repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        files: \.rs$
        args: [--all, --check]
        pass_filenames: false
        stages: [pre-commit]
        
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: system
        files: \.rs$
        args: [--all-targets, --all-features, --, -D, warnings]
        pass_filenames: false
        stages: [pre-commit, pre-push]
        
      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        files: \.rs$
        args: [--workspace, --all-features]
        pass_filenames: false
        stages: [pre-commit, pre-push]
