[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.29.0"
# CI backends to support
ci = "github"
# Tag pattern for releases (supports prefixed tags from release-plz)
tag-namespace = "redisctl"
# Allow manual workflow edits without errors
allow-dirty = ["ci"]
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Checksums to generate for each App
checksum = "sha256"
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["LICENSE-MIT", "LICENSE-APACHE", "README.md"]

# Publish to Homebrew tap (can be configured later)
# tap = "joshrotenberg/homebrew-tap"
# formula = "redisctl"
