[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.29.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Build only the main unified binary by default
# Users who want cloud-only or enterprise-only can build from source

# Create checksums for artifacts
checksum = "sha256"

# Include these files in archives  
include = ["LICENSE-MIT", "LICENSE-APACHE", "README.md"]

# Publish to Homebrew tap (can be configured later)
# tap = "joshrotenberg/homebrew-tap"
# formula = "redisctl"
