# Redis Enterprise Test Environment
# 
# Usage:
#   docker compose up -d        # Start enterprise and initialize cluster
#   docker compose logs init    # Check initialization status
#   docker compose down -v      # Clean up everything

services:
  # Redis Enterprise server
  enterprise:
    image: ${REDIS_ENTERPRISE_IMAGE:-redislabs/redis:latest}
    container_name: redis-enterprise
    cap_add:
      - SYS_RESOURCE
    ports:
      - "9443:9443"   # REST API
      - "8443:8443"   # Web UI  
      - "12000:12000" # Database port
    environment:
      ACCEPT_EULA: "yes"
    volumes:
      - enterprise-data:/var/opt/redislabs
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/v1/bootstrap"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - redis-net

  # Initialize cluster and create database
  init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-enterprise-init
    restart: "no"
    depends_on:
      enterprise:
        condition: service_healthy
    environment:
      REDIS_ENTERPRISE_URL: "https://enterprise:9443"
      RUST_LOG: ${RUST_LOG:-info}
    networks:
      - redis-net
    command: |
      sh -c '
      echo "========================================" &&
      echo "Initializing Redis Enterprise cluster..." &&
      echo "========================================" &&
      
      # Initialize cluster
      redisctl enterprise workflow init-cluster \
        --insecure \
        --name "test-cluster" \
        --username "admin@redis.local" \
        --password "Redis123!" \
        --accept-eula &&
      
      echo "" &&
      echo "========================================" &&
      echo "Creating test database..." &&
      echo "========================================" &&
      
      # Create database using the workflow
      redisctl enterprise workflow create-database \
        --insecure \
        --name "test-db" \
        --memory 100MB \
        --port 12000 &&
      
      echo "" &&
      echo "========================================" &&
      echo "Setup complete!" &&
      echo "" &&
      echo "Web UI: https://localhost:8443" &&
      echo "Username: admin@redis.local" &&
      echo "Password: Redis123!" &&
      echo "" &&
      echo "API: https://localhost:9443" &&
      echo "Database: redis://localhost:12000" &&
      echo "========================================" &&
      
      # List databases to confirm
      redisctl enterprise database list --insecure --output table
      '

networks:
  redis-net:
    driver: bridge

volumes:
  enterprise-data: