[workspace]
# Enable changelog generation
changelog_update = true

# Customize changelog
changelog_config = "cliff.toml"

# Dependencies update
dependencies_update = true

# Git configuration
allow_dirty = false
git_release_enable = false  # Let cargo-dist handle GitHub releases to avoid conflicts
git_tag_enable = true

# PR settings
pr_labels = ["release"]

# Publish settings
publish = true
publish_allow_dirty = false

[[package]]
name = "redis-cloud"
changelog_update = true

[[package]]
name = "redis-enterprise"
changelog_update = true

[[package]]
name = "redisctl"
# Main CLI, depends on all others
changelog_update = true
release = true  # Creates tags for cargo-dist to handle