# mdbook-lint configuration for redisctl documentation
# https://github.com/joshrotenberg/mdbook-lint

# Temporarily disable rules with known issues
disabled-rules = [
    "MDBOOK010",  # Math block detection - false positives with $ in shell code blocks (issue #141)
    "MDBOOK005",  # Orphaned files - incorrectly checking outside src directory (issue #142)
    "MDBOOK002",  # Internal link validation - false positives with existing files
]

# Don't fail the build on warnings, but show them for fixing
fail-on-warnings = false
fail-on-errors = false

# Enable rules that should be fixable
[rules.MD022]
# Require blank lines around headings 
enabled = true

[rules.MD032]
# Require blank lines around lists
enabled = true

[rules.MD031]
# Require blank lines around fenced code blocks
enabled = true

[rules.MD006]
# Lists should start at beginning of line
enabled = true

[rules.MD047]
# Files should end with single newline
enabled = true

# Configure specific rules
[rules.MD013]
# Allow longer lines for code examples and CLI output
line_length = 120

[rules.MD024]
# Allow duplicate headings in different sections
enabled = true

[rules.MD041]
# Require first line to be a heading
enabled = true

# Future configuration options when issues are resolved:
# [rules.MDBOOK005]
# search-path = "src"  # Only check within src directory
# 
# [rules.MDBOOK010]  
# skip-code-blocks = true  # Skip math detection in code blocks