[book]
authors = ["Josh Rotenberg"]
language = "en"
src = "src"
title = "redisctl Documentation"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/joshrotenberg/redisctl"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/joshrotenberg/redisctl/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1

# Enable mdbook-lint preprocessor
# Configuration is in .mdbook-lint.toml
[preprocessor.lint]
command = "mdbook-lint"
