enabled-categories = []
disabled-categories = []
enabled-rules = [
    'MD001',
    'MD002',
    'MD003',
    'MD004',
    'MD005',
    'MD006',
    'MD007',
    'MD009',
    'MD010',
    'MD011',
    'MD012',
    'MD013',
    'MD014',
    'MD018',
    'MD019',
    'MD020',
    'MD021',
    'MD022',
    'MD023',
    'MD024',
    'MD025',
    'MD026',
    'MD027',
    'MD028',
    'MD029',
    'MD030',
    'MD031',
    'MD032',
    'MD033',
    'MD034',
    'MD035',
    'MD036',
    'MD037',
    'MD038',
    'MD039',
    'MD040',
    'MD041',
    'MD042',
    'MD043',
    'MD044',
    'MD045',
    'MD046',
    'MD047',
    'MD048',
    'MD049',
    'MD050',
    'MD051',
    'MD052',
    'MD053',
    'MD054',
    'MD055',
    'MD056',
    'MD058',
    'MD059',
    'MDBOOK001',
    'MDBOOK002',
    'MDBOOK003',
    'MDBOOK004',
    'MDBOOK005',
    'MDBOOK006',
    'MDBOOK007',
    'MDBOOK008',
    'MDBOOK009',
    'MDBOOK010',
    'MDBOOK011',
    'MDBOOK012',
    'MDBOOK025',
]
disabled-rules = []
deprecated-warning = 'warn'
markdownlint-compatible = false
fail-on-warnings = false
fail-on-errors = true
malformed-markdown = 'warn'
