name: Cargo Deny

on:
  push:
    branches: [ main ]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
      - '.github/workflows/cargo-deny.yml'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
      - '.github/workflows/cargo-deny.yml'
  schedule:
    - cron: '0 0 * * MON'  # Weekly on Monday

jobs:
  cargo-deny:
    name: License and Security Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent duplicate runs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.checks }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a  # stable
        with:
          toolchain: stable

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.16.2

      - name: Run cargo-deny
        run: cargo deny --all-features check ${{ matrix.checks }}