name: Docker Test

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '.github/workflows/docker-test.yml'
      - 'crates/**'
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile'
      - '.github/workflows/docker-test.yml'
      - 'crates/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  docker-test:
    name: Docker Compose Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker Compose test cascade
        run: |
          docker compose up --abort-on-container-exit --exit-code-from test-redis
          EXIT_CODE=$?
          docker compose logs
          docker compose down -v
          exit $EXIT_CODE

      - name: Cleanup
        if: always()
        run: docker compose down -v