name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/mdbook.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/mdbook.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache mdbook-lint
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/mdbook-lint
          key: mdbook-lint-0.11.5-${{ runner.os }}

      - name: Install mdbook-lint 0.11.5
        run: |
          if ! command -v mdbook-lint || [ "$(mdbook-lint --version | cut -d' ' -f2)" != "0.11.5" ]; then
            cargo install mdbook-lint --version 0.11.5 --locked
          fi

      - name: Lint book
        run: |
          cd docs
          # Using || true due to false positives with internal link validation
          # MDBOOK002 is disabled but still reports errors in some cases
          # We still get value from other lint checks without failing CI
          mdbook-lint lint src || true

      - name: Build book
        run: |
          cd docs
          mdbook build

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book

  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4